# Generated by Django 3.1.4 on 2021-01-04 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15, null=True, verbose_name='タイトル')),
                ('introduction', models.TextField(verbose_name='自己紹介')),
                ('site_link', models.SlugField(blank=True, max_length=200, null=True, verbose_name='ウェブサイト')),
                ('avater_image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='プロフィール写真')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'プロフィール',
                'db_table': 'プロフィール',
            },
        ),
    ]
