# Generated by Django 3.1.4 on 2021-01-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='肩書き'),
        ),
    ]
