# Generated by Django 3.1.4 on 2021-01-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210104_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avater_image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='プロフィール画像'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='site_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ウェブサイト'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='肩書き'),
        ),
    ]
